### ISSUE TITLE
Fabric: bugfix

### ISSUE THREAD

**Issue by Monserg** [GolosChain/golos-ios#53]
Исправление крашей приложения в разрезе билдов

**Comment by Monserg** [comment]
1. build 1.0.16 (исправления включены в build 1.0.17):

- [x] ReplyTableViewCell.swift line 218 (https://fabric.io/goloschain/ios/apps/io.golos.testing.golos-ios/issues/5b76bb5c6007d59fcd0b7b30?time=last-seven-days):
     добавил проверку на пустое значение для даты created; исправление сделано на стороне библиотеки GoloSwift.

- [x] WebSocketManager.swift line 189 (https://fabric.io/goloschain/ios/apps/io.golos.testing.golos-ios/issues/5b71409f6007d59fcda45de8/sessions/latest?build=85164693):
    добавил проверку на nil после 188 строки кода; исправление сделано на стороне библиотеки GoloSwift.

- [x] LogInShowInteractor.swift line 41 (https://fabric.io/goloschain/ios/apps/io.golos.testing.golos-ios/issues/5b73d2ce6007d59fcdd4694c?time=last-seven-days):
    добавил проверку на nil для privateKey в 40 строке кода; если ключ не создался - вернется false и пользователь увидит сообщение об ошибке.

- [x] TagsCollectionViewController.swift (https://fabric.io/goloschain/ios/apps/io.golos.testing.golos-ios/issues/5b754a4a6007d59fcdefa94e?time=last-seven-days):
    добавил ...

- [x] TagsCollectionViewController.swift line 98 (https://fabric.io/goloschain/ios/apps/io.golos.testing.golos-ios/issues/5b7a73746007d59fcd4ad759?time=last-seven-days):
    в строке 99 изменил формирование IndexPath на использование insertIndexPath; старый вариант закомментировал.

- [x] PostCreateInteractor.swift line 87 (https://fabric.io/goloschain/ios/apps/io.golos.testing.golos-ios/issues/5b7551016007d59fcdf039bc?time=last-seven-days):
